# Generated by Django 4.0.6 on 2022-07-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videotag',
            name='tag',
            field=models.CharField(max_length=128, unique=True, verbose_name='Tag'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='thumbnail',
            field=models.CharField(max_length=128, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='title',
            field=models.CharField(max_length=128, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='youtubevideo',
            name='url',
            field=models.CharField(max_length=128, verbose_name='URL'),
        ),
    ]
