# Generated by Django 4.0.6 on 2022-07-27 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeAPI', '0002_alter_videotag_tag_alter_youtubevideo_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videotag',
            options={'verbose_name': 'Video Tag', 'verbose_name_plural': 'Video Tags'},
        ),
        migrations.AlterModelOptions(
            name='youtubevideo',
            options={'verbose_name': 'Youtube Video', 'verbose_name_plural': 'Youtube Videos'},
        ),
    ]
