# Generated by Django 4.0.6 on 2022-07-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeAPI', '0003_alter_videotag_options_alter_youtubevideo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='youtubevideo',
            name='view_count',
            field=models.IntegerField(default=0, verbose_name='View Count'),
            preserve_default=False,
        ),
    ]
